Repository beanbeanjuice/back-to-the-jungle, pull requests merged in 2023-06, with the labels that each got.

#96 Switched String Lookup to Hash
  Jetpack/Assets/Scripts/Fish/FishFactory.cs
  Jetpack/Assets/Scripts/LevelLoader.cs
  developer_logs/William.md
Labels: bug, small

#102 Add Scene Transitions
  Jetpack/Assets/Resources/Prefabs/LevelLoader.prefab
  Jetpack/Assets/Resources/Prefabs/LoadDelay.prefab
  Jetpack/Assets/Resources/Prefabs/LoadDelay.prefab.meta
  Jetpack/Assets/Scenes/Gameplay.unity
  Jetpack/Assets/Scenes/StartMenu.unity
  Jetpack/Assets/Scenes/StartScreen.unity
  Jetpack/Assets/Scripts/Scenes.meta
  Jetpack/Assets/Scripts/Scenes/GameStartDelay.cs
  Jetpack/Assets/Scripts/Scenes/GameStartDelay.cs.meta
  Jetpack/Assets/Scripts/Scenes/LevelLoader.cs
  Jetpack/Assets/Scripts/Scenes/LevelLoader.cs.meta
  Jetpack/Assets/Scripts/Scenes/LoadDelay.cs
  Jetpack/Assets/Scripts/Scenes/LoadDelay.cs.meta
  Jetpack/Assets/Scripts/test.cs
  Jetpack/Assets/Scripts/test.cs.meta
Labels: bug, feature, CRITICAL

#107 Added Parallelx Background Sprites
  Jetpack/Assets/Prefabs.meta
  Jetpack/Assets/Resources/Prefabs/Ground 1.prefab
  Jetpack/Assets/Resources/Prefabs/Ground 1.prefab.meta
  Jetpack/Assets/Resources/Sprites/Background/backTrees_layer3.png
  Jetpack/Assets/Resources/Sprites/Background/backTrees_layer3.png.meta
  Jetpack/Assets/Resources/Sprites/Background/darkBush_layer2.png
  Jetpack/Assets/Resources/Sprites/Background/darkBush_layer2.png.meta
  Jetpack/Assets/Resources/Sprites/Background/frontTrees_layer1.png
  Jetpack/Assets/Resources/Sprites/Background/frontTrees_layer1.png.meta
  Jetpack/Assets/Resources/Sprites/Background/grass_layer0.png
  Jetpack/Assets/Resources/Sprites/Background/grass_layer0.png.meta
  Jetpack/Assets/Resources/Sprites/Background/lightBush_layer4.png
  Jetpack/Assets/Resources/Sprites/Background/lightBush_layer4.png.meta
  Jetpack/Assets/Resources/Sprites/Background/sky_layer5.png
  Jetpack/Assets/Resources/Sprites/Background/sky_layer5.png.meta
  Jetpack/Assets/Sprites.meta
  Jetpack/Assets/Sprites/Background.meta
Labels: MAIN: Animation and Visuals

#119 Fixed Flying Bug on Lower FPS Machines
  Jetpack/Assets/Resources/Sprites/Background/Ground/ground.prefab
  Jetpack/Assets/Scripts/Camera/.idea/.idea.Camera.dir/.idea/workspace.xml
  Jetpack/Assets/Scripts/Player/PlayerMovementController.cs
  developer_logs/William.md
Labels: bug, small, MAIN: Movement/Physics, CRITICAL

#122 120 gameplay fast cutscene
  Jetpack/Assets/Resources/Sprites/GameStartCutscene.meta
  Jetpack/Assets/Resources/Sprites/GameStartCutscene/lab_background.jpeg
  Jetpack/Assets/Resources/Sprites/GameStartCutscene/lab_background.jpeg.meta
  Jetpack/Assets/Resources/Sprites/GameStartCutscene/portal.png
  Jetpack/Assets/Resources/Sprites/GameStartCutscene/portal.png.meta
  Jetpack/Assets/Resources/Sprites/GameStartCutscene/tesseract.png
  Jetpack/Assets/Resources/Sprites/GameStartCutscene/tesseract.png.meta
  Jetpack/Assets/Scenes/GameStartCutscene.unity
  Jetpack/Assets/Scenes/GameStartCutscene.unity.meta
  Jetpack/Assets/Scenes/StartMenu.unity
  Jetpack/Assets/Scenes/Timeline.meta
  Jetpack/Assets/Scenes/Timeline/Timeline.playable
  Jetpack/Assets/Scenes/Timeline/Timeline.playable.meta
  Jetpack/Assets/Scripts/Scenes/LevelLoader.cs
  Jetpack/Assets/Scripts/Scenes/StartGame.cs
  Jetpack/Assets/Scripts/Scenes/StartGame.cs.meta
  Jetpack/ProjectSettings/EditorBuildSettings.asset
  Jetpack/ProjectSettings/TagManager.asset
  Jetpack/ProjectSettings/TimelineSettings.asset
Labels: MAIN: Animation and Visuals

#127 FEATURE - Bird Factory
  Jetpack/Assets/Resources/Prefabs/BirdWarning.prefab
  Jetpack/Assets/Resources/Prefabs/Bluebird.prefab
  Jetpack/Assets/Resources/Prefabs/Fish.prefab
  Jetpack/Assets/Resources/Prefabs/Pinkbird.prefab
  Jetpack/Assets/Scenes/Gameplay.unity
  Jetpack/Assets/Scripts/Birds.meta
  Jetpack/Assets/Scripts/Birds/BirdController.cs
  Jetpack/Assets/Scripts/Birds/BirdController.cs.meta
  Jetpack/Assets/Scripts/Birds/BirdFactory.cs
  Jetpack/Assets/Scripts/Birds/BirdFactory.cs.meta
  Jetpack/Assets/Scripts/Birds/WarningController.cs
  Jetpack/Assets/Scripts/Birds/WarningController.cs.meta
  Jetpack/Assets/Scripts/Player/PlayerController.cs
  Jetpack/ProjectSettings/TagManager.asset
Labels: MAIN: Game Logic, in progress

#139 Walking audio
  Jetpack/Assets/Resources/Audio/Music/Atomic Amnesia MMX - 3kliksphilip.wav.meta
  Jetpack/Assets/Resources/Audio/Music/README.md
  Jetpack/Assets/Resources/Audio/SFX/Free Walking fast on Dirt Sound Effect [Foley].mp3
  Jetpack/Assets/Resources/Audio/SFX/Free Walking fast on Dirt Sound Effect [Foley].mp3.meta
  Jetpack/Assets/Resources/Audio/SFX/README.md
  Jetpack/Assets/Resources/Audio/SFX/pufferfish.wav
  Jetpack/Assets/Resources/Audio/SFX/pufferfish.wav.meta
  Jetpack/Assets/Scenes/Gameplay.unity
  Jetpack/Assets/Scripts/Player/PlayerAudioManager.cs
  Jetpack/Assets/Scripts/Player/PlayerAudioManager.cs.meta
  Jetpack/Assets/Scripts/Player/PlayerMovementController.cs
  developer_logs/Westley.md
Labels: SUB: Audio

#143 128 increase player speed
  Jetpack/Assets/Scenes/Gameplay.unity
  Jetpack/Assets/Scripts/Mount/MountAnimationController.cs
  Jetpack/Assets/Scripts/Player/PlayerMovementController.cs
Labels: SUB: Game Feel

#147 Linted Codebase
  Jetpack/Assets/Packages/EPPlus.6.2.4/readme.md
  Jetpack/Assets/Packages/Microsoft.IO.RecyclableMemoryStream.2.2.1/README.md
  Jetpack/Assets/Scripts/Birds/BirdFactory.cs
  Jetpack/Assets/Scripts/Player/PlayerAudioManager.cs
  Jetpack/Assets/Scripts/Player/PlayerMovementController.cs
  Jetpack/Assets/Scripts/Scenes/ShopMenu.cs
  press_kit/press_kit.md
Labels: bug, small, SUB: Producer
